### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by marcominerva** [n3wt0n/BugGuardian#1]
I have downloaded the project as ZIP. I obtain the following error during compilation:

This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\packages\Microsoft.Net.Compilers.1.0.0\build\Microsoft.Net.Compilers.props.	

Project: BugGuardian.TestCallerWeb
File: BugGuardian.TestCallerWeb.csproj

**Comment by n3wt0n** [comment]
THe problem was alredy fixed on the commit 'bfd30627d56b2f0d43def432714a1ed41ed77f13'
